### ISSUE TITLE
backpack not showing

### ISSUE THREAD

**Issue by phonkv2** [yesod404/yesodCollyHUD#4]
im facing a issue with the backpack not showing up any fix?

![image](https://github.com/yesod404/yesodCollyHUD/assets/82752413/5fa63090-45da-403f-9552-f7c233812d86)

**Comment by yesod404** [comment]
I am not entirely sure what could cause the problem. It was one of the first issues I fixed upon returning to this HUD, especially considering that no one else has brought this up to me.

Linked is the most recent build of the HUD, maybe that will be of better use. [Link](https://www.mediafire.com/file/tcell74v36d93bn/yesodCollyHUD.zip/file)

**Comment by phonkv2** [comment]
> I am not entirely sure what could cause the problem. It was one of the first issues I fixed upon returning to this HUD, especially considering that no one else has brought this up to me.
> 
> Linked is the most recent build of the HUD, maybe that will be of better use. [Link](https://www.mediafire.com/file/tcell74v36d93bn/yesodCollyHUD.zip/file)

ive tried everything i will the file you linked and let you know im on win 11 ive even tried some diffrent forks of the hud i was only able to get a part of the loadout to show but its all hidden to the side thats one or it just dosent appear

**Comment by phonkv2** [comment]
Ive tried the latest build it did not change at all i still see no backpack

**Comment by yesod404** [comment]
That is weird; it could be something about your PC or in your custom folder. What OS do you use? What else do you have in your custom folder?

**Comment by yesod404** [comment]
I released the release version of the HUD, the backpack completely changed so it should no longer be broken, let me know the status.

**Comment by phonkv2** [comment]
> That is weird; it could be something about your PC or in your custom folder. What OS do you use? What else do you have in your custom folder?

It couldnt be a pc issue since every other hud works just fine os is win 11 ive tried to remove everything from custom folder and just keep the hud in it and it still didnt work for me

**Comment by phonkv2** [comment]
> I released the release version of the HUD, the backpack completely changed so it should no longer be broken, let me know the status.

Hello thank you it works now sorry for responding late i had no time to play tf2 much thanks for the help

**Comment by yesod404** [comment]
No problem
